# Generated by Django 3.1.3 on 2021-10-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='qustion',
            new_name='question',
        ),
    ]
