# Generated by Django 3.1.3 on 2021-10-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20211020_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_view_list', 'Can View List')]},
        ),
    ]
